### ISSUE TITLE
Option to disable logs for KiCAD integration plugin

### ISSUE THREAD

**Issue by uranuspucksaxophone** [freerouting/freerouting#135]
First of all, thank you for taking the time to report an issue.

To make our work easier, please provide as many details as you can:
* [ ] What version of freerouting are you using?
The included with the plugin.
* [ ] Is fixing this issue critical for your work?
No.

**Comment by andrasfuchs** [comment]
It still some testing, but added the "-dl" command line argument to disable logging.

**Comment by andrasfuchs** [comment]
No, but logging is disabled by default for the KiCad plugin. 

I'm hesitant to change the GUI to be honest, because it would mean that we need to add new multilingual menuitems/strings, that would mean translating them into the 11 languages we support, and the GUI would need to much bigger overhaul in the long run anyway, if an UX designer could join the project.
