### ISSUE TITLE
Making code compatible with java 8

### ISSUE THREAD

**Issue by rusefi** [freerouting/freerouting#14]
Java 8 vs java 11 is a bit controversial - the fact that the industry choice to back-port fixes into 8 and provide support of java 8 speaks volume, also there is some licencing drama.

As long as it's trivial to do so I believe that it would be nicer to compile code with java 8 (as long as it does not use removed API) - this case all users from 8 to 13 would be able to run the code.

This could absolutely be revisited once/if there are additional arguments for java 9+.

**Comment by miho** [comment]
Personally, I see no point in supporting Java 8 anymore. So you are definitely right about it being controversial ;) We plan to ship an application with a "minimal" runtime (in Java-terms, which means probably 30MB compressed). So there's no real Java 8 vs. Java 11 issue for regular end-users. 

Since I maintain a lot of different repositories and cannot provide support for issues with multiple JVM versions. And although they are rare, they still exist and are sometimes hard to find and fix. I will keep my code compatible with the latest LTS release of the Java platform if possible. Sticking to an older release would only be an option for me if there's a large group of end-users that I'd prevent from using the application at all.

**Comment by rusefi** [comment]
Once this application is self-contained it can use any version of java and not care for the users, but as of today I did not have java 11 installed nor did my PCB contributer - we both only had java 8.

https://www.baeldung.com/java-in-2019 is probably not good user statistics but 80% usage of version 8 is a very serious which should not be ignored in my opinion.

**Comment by miho** [comment]
I am well aware of the statistics but since we agree that a self-contained app is the best solution anyway, that's not an issue. In the meantime people can use older binaries if they are unable to update their installation of Java. As of now, changes between older and newer versions of freerouting are not that huge.

**Comment by rusefi** [comment]
It is my experience that the target audience is very confused by "incompatible class version 53" message (from memory) - some of the target audience would miss the fact that JRE 11 is needed.

I would actually make an argument that current release title "JDK 11" instead of "Java 11" would confuse at least someone :)

Speaking of usability let me create a usability issue :)

**Comment by rusefi** [comment]
"self-contained app is the best solution anyway" I could be missing something.

Is self-contained app available as of today? Does freerouting.exe require external JRE as of today?

**Comment by miho** [comment]
I just uploaded an MSI-installer with an integrated runtime. The .EXE is not self-contained. I renamed it on the GitHub release page to indicate that. I will configure GitHub actions to automatically create release builds for Windows, macOS and Linux (including installers and/or app-bundles). This should simplify things for end-users.

**Comment by rusefi** [comment]
Sweet stuff :)

When you say macOS I think you really want to look at https://github.com/freerouting/freerouting/issues/9

**Comment by rusefi** [comment]
I've installed the amazing self-contained .MSI and JFrame title shows what seems to be wrong version number?

![image](https://user-images.githubusercontent.com/7377949/76708166-26964d00-66cb-11ea-8237-d0ebd9f0767a.png)

**Comment by miho** [comment]
That's a bug. The version should automatically update. But I forgot to add that to the build script.

**Comment by andrasfuchs** [comment]
Is my understanding correct that I can use Java 9+ constructs in the code, because you agreed to go with Java 11 and self-contained release files?

**Comment by rusefi** [comment]
what specific constructs of java 9 are you interested to use? at the moment only "var" was used about 8 times.

i guess the question is: do we believe in this jar used as a library in a near future? if this jar would be used as a library maybe that's a reason NOT to force java 11 on consumers?

if this is always a standalone tool and now we have self-contained release I guess there are little reasons to keep java 8 compatibility.

**Comment by andrasfuchs** [comment]
I can't say what I would actually use from the newer features, I worked mostly on C# projects in the past. 

So, I'm not really against Java 8, I just suppose that many improvements happened to Java (just like to C#) in the last 6 years, and it would be nice to benefit from them, that's all.

**Comment by rusefi** [comment]
I am a professional java developer and things are a bit more complicated with java 8 to 11 migration. java 11 has removed a few things (which were probably supposed to be removed) and this has thrown many legacy projects into issues

also Oracle licensing has changed. it's a complicated matter and I would prefer not to debate it. Please make your own research on the java 11 controversy if you are interested to have your own opinion.

as a professional java developer I have not yet seen benefits which justify the drama. "var" syntax sugar cannot be considered worth all the negative consequences in my opinion.

**Comment by miho** [comment]
The licensing issue is complex and a huge problem if users have to install their own JDK. This is unfortunately true for JDK 8 and 11 alike. So the real solution is to not force users to install Java at all.

**Comment by rusefi** [comment]
https://github.com/miho/freerouting/issues/19 created

I think the focus should be on how to bring two forks together and if https://github.com/miho/freerouting plans to merge into https://github.com/freerouting/freerouting

My preference would be for @miho and @andrasfuchs to make this decision without me. Any decision you guys make work for me, just make a decision and implement it.

**Comment by andrasfuchs** [comment]
@miho, I merged my last PR from my own repo today, and I'm not planning to keep my repo anymore.
Would you also consider completely moving the our upstream repo (this), since we are both collaborators here?

I'm going to resolve the merging conflicts soon, so when yours and this get into sync, we could theoretically stop commiting to miho, and move here. What do you think?

**Comment by miho** [comment]
Sounds good.
