### ISSUE TITLE
Handling of identifiers which use non-Windows-1252 characters

### ISSUE THREAD

**Issue by Rezer** [freerouting/freerouting#148]
This is more of a question than an issue, but after taking a good hard look at SpecctraDsnFileReader.java I realized that it's mostly auto-generated code with a smattering of manual coding to add the next_string() and next_string_list() functions.  As best as I can tell they were added to kind of circumvent the auto-generated code's inability to handle identifiers which use letters from non-ASCII alphabets.  The thing is, it actually looks like it might be fairly straightforward to just update the jflex definition file to support this in a way that would be more maintainable and less prone to cause other issues (See https://github.com/freerouting/freerouting/issues/143).

So, has this been considered/attempted before?  If not, would it be worthwhile to investigate and see if it's possible to get this working either without the next_string() functions or in a way that allows next_string() and next_string_list() to be moved outside of the auto-generated class?

**Comment by andrasfuchs** [comment]
I'm not sure if others attempted to update the jflex definition file before, I wasn't. I agree that theoretically that would be a better solution long term, I'm just a little hesitant because at this point the DSN reader works okay for the most cases, and the jflex update would potentially introduce new bugs and/or challenges.

If you feel like going deeper and do the update, I gladly review and test it, but I'm planning to spend the little spare time I have on other issues. Let me know what you think!
