### ISSUE TITLE
Binaries are not generated for the release

### ISSUE THREAD

**Issue by andrasfuchs** [freerouting/freerouting#24]
Binaries are not generated for the release after it was created here, in this repo.

I got the following error:
![image](https://user-images.githubusercontent.com/910321/79684344-d6ae2700-8230-11ea-98b2-9e3c3d6e9162.png)

**Comment by andrasfuchs** [comment]
I don't have the error now, but the binaries are not generated, they are not listed by the release.

![image](https://user-images.githubusercontent.com/910321/79694600-a20e8f80-8271-11ea-971c-26d925879a7c.png)

**Comment by miho** [comment]
Looks like you didn't trigger the create-release workflow this time. Usually, this happens if the release wasn't fully deleted (including associated tags). See the test release [v0.0.0](https://github.com/freerouting/freerouting/releases/tag/v0.0.0) for which installers are generated. To see which workflows are/were running, see https://github.com/freerouting/freerouting/actions. BTW. documentation for GH Actions can be found here: https://help.github.com/en/actions

**Comment by andrasfuchs** [comment]
Great, thank you for the details. I needed to delete the tag as well and recreate the release. 
It looks good now.
