### ISSUE TITLE
WARN  Non-ansi character '{' 

### ISSUE THREAD

**Issue by JMRoderick** [freerouting/freerouting#270]
2024-02-20 01:50:32.900 [AWT-EventQueue-0] WARN  Non-ansi character '{' found at position 1107209 just after '/~{BT-MD}'.
2024-02-20 01:50:32.901 [AWT-EventQueue-0] WARN  Non-ansi character '}' found at position 1107213 just after '/~{BT-MD}'.

java 17 on ubuntu x64 from KiCad
freerouting-1.9.0.jar

An exported .DSN file from KiCad has no problems.
Reloading a .DSN file that was saved from freerouting does.

It is complaining that the '{' and '}' characters are non-ansi.
Well , thats obviously not true , the chart says they are 123 and 125.

These characters are used to produce an overline on the net label strings in KiCad.
An example is   ~{WE}   ,  if this is my net label string  ,  then it will show WE with a line over it denoting an active low signal.

I replaces all the '{' and '}' with underscores and the errors went away , but
all the nets are no longer routed.

odd that the original export fomr KiCad has { and } in it , and it does not complain.

I saved this as a .DSN because it was running the postroute optimization for 7 days and would never finish.
Now I can not seem to get it imported back into freeroute.

Thx

**Comment by andrasfuchs** [comment]
@JMRoderick I have just tried to reproduce the problem you are having with the { } characters. I agree with you that you should not get the error since { } are ANSI, but no matter what I did with my DSN files, I could not get the warning/error.

Could you upload the DSN file you exported from KiCad or the KiCad project file so that I can investigate further?
What exact version of KiCad did you use?

Regardless of the non-ansi warning, I think the postroute-optimization should never take that long, so that's another issue that I could look into.

Thank you for your report!
