### ISSUE TITLE
Damaged Mac .DMG file for current version.

### ISSUE THREAD

**Issue by roontoon** [freerouting/freerouting#63]
First of all, thank you for taking the time to report an issue.

To make our work easier, please provide as many details as you can:

* [x] On what platform did you run it?  
MacOS
Running Big Sir 15.2
Cannot download due to a damaged file error. Have downloaded many times with same result.

[freerouting0.pdf](https://github.com/freerouting/freerouting/files/7049820/freerouting0.pdf)

**Comment by andrasfuchs** [comment]
Could you check the latest snapshot release, please?
You can get it from here: https://github.com/freerouting/freerouting/releases/tag/SNAPSHOT

**Comment by roontoon** [comment]
Sorry. Doesn’t work

**Comment by Laughy10704** [comment]
The jar file from the latest snapshot works, but I can confirm I have the same problem as roontoon with the .dmg file

**Comment by andrasfuchs** [comment]
Thank you guys for the quick reply. I'll let you know here if I have a new .dmg to test.

**Comment by pierremolinaro** [comment]
I agree, same problem for me.

I have ran :

xattr -d com.apple.quarantine <path to>Freerouting.app

it solves the problem for me, I don't know if this is a reliable solution.

I have read the create-distribution-macos.sh script, surprisingly it does not use apple ID. So I suggest the DMG file to contain not the application, but a .pkg file that installs the signed application. 

I have my own Freerouting distribution, and I perform the following steps:
rm -fr Freerouting-1.4.4-pm.app
/Volumes/dev-svn/ElCanari-dev/freerouting-pm/jdk14/jdk-14.jdk/Contents/Home/bin/jpackage --input /Volumes/dev-svn/ElCanari-dev/freerouting-pm/freerouting/build/dist/ --name Freerouting-1.4.4-pm --main-jar freerouting-executable.jar --type app-image --runtime-image jdk14/runtime --app-version 1.4.4-pm
/usr/bin/codesign --force --sign 'Apple Development: ***@***.***' --deep Freerouting-1.4.4-pm.app
/usr/bin/codesign -dv --verbose=4 Freerouting-1.4.4-pm.app
/bin/rm -rf Freerouting-1.4.4-pm
/bin/rm -f Freerouting-1.4.4-pm.dmg
/bin/mkdir Freerouting-1.4.4-pm
/bin/cp Freerouting-1.4.4-pm.pkg Freerouting-1.4.4-pm
/usr/bin/hdiutil create -srcfolder Freerouting-1.4.4-pm Freerouting-1.4.4-pm.dmg -fs HFS+
/bin/rm Freerouting-1.4.4-pm.pk
/bin/rm -rf Freerouting-1.4.4-pm

Note jpackage is called with --type app-image option.

***@***.*** is the email address associated with my Apple ID used in Xcode.

Hope that helps,

Pierre Molinaro

**Comment by andrasfuchs** [comment]
@pierremolinaro, have you tried [the --mac-sign jpackage parameter](https://docs.oracle.com/en/java/javase/14/docs/specs/man/jpackage.html) by any chance?

Would any of you guys consider making a pull request with the needed changes in the [create-distribution-macos.sh](https://github.com/freerouting/freerouting/blob/master/distribution/create-distribution-macos.sh) script to produce a signed DMG file? 

The script can be run locally of course, but it will eventually run on a GitHub VM after every push to the repo. 
You can find more info about the macOS runner here: 
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
We use `macos-latest` so Catalina 10.15.


It would be a great help for all the macOS users out there.

**Comment by pierremolinaro** [comment]
I also use Catalina for my application development.

I have tried —mac-sign without any success, the jpackage exits on error. However, many other options should be provided : --mac-signing-key-user-name, --mac-bundle-signing-prefix, --mac-signing-keychain.

So I find that using codesign is simpler.

I do not know if it is possible to get a signed mac application without any Apple ID :
	https://developer.apple.com/forums/thread/682871 <https://developer.apple.com/forums/thread/682871>

Signing an application on OSx is a nightmare, I spent hours before finding a solution that seemed to work. I think my applications are running from El Capitan to Big Sur.

But maybe there is a better solution, I'm not an expert in application signing.

Pierre

**Comment by pierremolinaro** [comment]
Maybe there is a way to have a single development script, valid for all users.

Assuming that the user who wants to distribute the application has a Developer ID, he can get it by running :

security find-identity -v -p codesigning

On my Mac it displays:
  1) 70xxxxxx85 "Apple Development: ***@***.*** (U399CP39LD)"
     1 valid identities found

70xxxxxx85 is SHA1 key associated with my developer account.

/usr/bin/codesign --force --sign 'Apple Development: ***@***.*** (U399CP39LD)' --deep Freerouting-1.4.4-pm.app
is ok.

Using the SHA1 works also fine:
/usr/bin/codesign --force --sign 70xxxxxx85 --deep Freerouting-1.4.4-pm.app

However it requires few step to extract the account string from security tool response. And perhaps an user may have more than one account.

Pierre

**Comment by andrasfuchs** [comment]
Hmm, I never had an Apple Developer account before, so I started my registration today with my Apple ID. 

Do I understand it correctly that it costs ~100 USD/year just to have this type of account?

**Comment by pierremolinaro** [comment]
No, it is free. After download Xcode and add account in Xcode Preferences > Account.

Pierre

**Comment by andrasfuchs** [comment]
Xcode is only on macOS, right? I don't have a Mac :/ 
I suspect that it would somehow be possible to run a Mac virtual machine on Windows, but I have no experience with that.

**Comment by pierremolinaro** [comment]
Yes, Xcode only runs on OSX.

Unfortunately, Apple does not support the installation of OSX on a machine other than a Mac, and, worse, does everything possible to make it very difficult, if not impossible. Installing OSX on a PC is a hack, nothing ensures stability or durability

The simplest solution is for someone with a Mac to build the distribution.

If you want, I can try to build a Python script that makes the operation simple.

Pierre

**Comment by andrasfuchs** [comment]
I don't know if it is more difficult, but could you try to change our existing [create-distribution-macos.sh](https://github.com/freerouting/freerouting/blob/master/distribution/create-distribution-macos.sh)?

There is a good chance that if you could make that work then I could integrate it into our build actions on GitHub.

**Comment by pierremolinaro** [comment]
I will first begin to try to adapt my python script. I think Python is very much simpler for all text manipulations. For example, how in Shell script extract the Developer ID from the answer of security find-identity -v -p codesigning ?

A Python script can be called as a Shell script.

Pierre

**Comment by andrasfuchs** [comment]
Regarding to the Developer ID: GitHub is able to store secrets in a way that they will be pasted into the build process. Practically this means that the script should expect the Developer ID as a parameter.

A shell script would be better just because we already have one that runs on GitHub, but it's very likely that a Python script is okay as well. Your solution sounds great, thank you, could you share your script so I can test it?

Are you 100% sure that the Apple Developer ID is free? I asked another developer who has one, and he said that he pays for it. 
I would prefer to have our own signature for Freerouting, but if there is no free way to sign it then as a last resort my friend would be ok with sharing his ID with us for signing.

**Comment by pierremolinaro** [comment]
The Developer ID it self is not a secret. You can find with codesign utility the developer ID used for signing an application. But, if you do not own the developper ID, you can do nothing with it. Trying to sign an application with it is rejected.

Of course, you can freely use my script if you find it useful. You can share it, distribute it, as you want.

Yes, having a Developer ID is free. I have one for years, and never pay anything. Apple information is not very clear, everything is made that the user pays a registration. You should have a paid Developer ID if you want to distribute your application via the Apple Store.

I don't know if it is possible to share a developer ID between several developers. I think the easiest way is to have someone with Xcode and a developer ID build and sign the FreeRouting application.

**Comment by andrasfuchs** [comment]
I see, ok, thank you for the explanation!

Could you make your script available for me?

**Comment by pierremolinaro** [comment]
Yes, of course, you can freely use the script I have sent.

I can also send you a DMG built with my script, for checking the application signature is ok.

Pierre

**Comment by andrasfuchs** [comment]
Hi Pierre, 

I don't think I got it, probably because GitHub strips e-mail attachments, as far as I know. 
Could you copy the whole script into your reply's text?

Thanks!

**Comment by pierremolinaro** [comment]
Ah, ok, I understand. Sorry, I was thinking you have it. Otherwise, if you have an email address outside Github, I can send it in attached file.



#! /usr/bin/env python
# -*- coding: UTF-8 -*-

#------------------------------------------------------------------------------
# https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html
#------------------------------------------------------------------------------

import sys, os, subprocess

#------------------------------------------------------------------------------
#   FOR PRINTING IN COLOR
#------------------------------------------------------------------------------

BLACK = '\033[90m'
RED = '\033[91m'
GREEN = '\033[92m'
YELLOW = '\033[93m'
BLUE = '\033[94m'
MAGENTA = '\033[95m'
CYAN = '\033[96m'
WHITE = '\033[97m'
ENDC = '\033[0m'
BOLD = '\033[1m'
UNDERLINE = '\033[4m'
BLINK = '\033[5m'

#------------------------------------------------------------------------------
#   RUN COMMAND
#------------------------------------------------------------------------------

def runCommand (command) :
  s = MAGENTA + BOLD + "+"
  for c in command :
    if " " in c :
      s += " '" + c + "'"
    else :
      s += " " + c
  s += ENDC
  print (s)
  childProcess = subprocess.Popen (command)
  childProcess.wait ()
  if childProcess.returncode != 0 :
    sys.exit (childProcess.returncode)

#------------------------------------------------------------------------------
#   runHiddenCommand
#------------------------------------------------------------------------------

def runHiddenCommand (cmd, logUtilityTool=False) :
  s = MAGENTA + BOLD + "+"
  for c in cmd :
    if " " in c :
      s += " '" + c + "'"
    else :
      s += " " + c
  s += ENDC
  print (s)
  result = ""
  childProcess = subprocess.Popen (cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True)
  while True:
    line = childProcess.stdout.readline ()
    if line != "":
      result += line
    else:
      childProcess.wait ()
      if childProcess.returncode != 0 :
        sys.exit (childProcess.returncode)
      return result

#------------------------------------------------------------------------------
#   MAIN
#------------------------------------------------------------------------------

DMG_CONTAINS_APP = True
DMG_CONTAINS_PKG = False
#---------- First argument is the version number
APP_VERSION = "?"
if len (sys.argv) < 2 :
  print (BOLD + RED + "Error, argument missing, usage: " + os.path.basename (sys.argv [0]) + " version_string" + ENDC)
  sys.exit (1)
else:
  APP_VERSION = sys.argv [1]
#---------- Get script absolute path
scriptDir = os.path.dirname (os.path.abspath (sys.argv [0]))
#---------- Free routing dir
FREEROUTING_DIR = scriptDir + "/.."
#---------- Goto Freerouting dir
os.chdir (FREEROUTING_DIR)
#---------- Get Developer ID
response = runHiddenCommand (["security", "find-identity", "-v", "-p", "codesigning"])
print (response)
responseComponents = response.split ('"')
developerIDString = ""
if len (responseComponents) < 3 :
  print (BOLD + RED + "Error, no valid Apple Developer ID" + ENDC)
  sys.exit (1)
elif len (responseComponents) == 3 :
  developerIDString = responseComponents [1]
  if developerIDString.startswith ("Apple Development: ") :
    print (BOLD + "Success: found Developer ID: '" + developerIDString + "'")
  else:
    print (BOLD + RED + "Error: Developer ID: '" + developerIDString + "' does not start with 'Apple Development: '")
#---------- Compile for distribution
runCommand (["bash", "gradlew", "dist"])
print (BLUE + BOLD + "COMPILATION DONE" + ENDC)
#---------- JDK directory
JPKG_DIR = scriptDir + "/.jdk14"
#---------- Download and install JDK
# https://jdk.java.net/14/
JPACKAGE_JVM="https://download.java.net/java/GA/jdk14/076bab302c7b4508975440c56f6cc26a/36/GPL/openjdk-14_osx-x64_bin.tar.gz"
JPKG_HOME = JPKG_DIR + "/jdk-14.jdk/Contents/Home"
JPKG_ARCHIVE = "jdk14.tar.gz"
if os.path.exists (JPKG_HOME) :
  print (BLUE + BOLD + "JDK already installed" + ENDC)
else:
  if not os.path.exists (JPKG_DIR) :
    runCommand (["mkdir", "-p", JPKG_DIR])
  os.chdir (JPKG_DIR)
  #---------- Download ?
  if not os.path.exists (JPKG_ARCHIVE) :
    print (BLUE + "Download JDK" + ENDC)
    runCommand (["curl", "-o", JPKG_ARCHIVE, JPACKAGE_JVM])
  #---------- Install ?
  if not os.path.exists (JPKG_DIR + "/runtime") :
    print (BLUE + "Unpack JDK" + ENDC)
    runCommand (["tar", "xvzf", JPKG_ARCHIVE])
    print (BLUE + "Create runtime image" + ENDC)
    runCommand ([
      JPKG_HOME + "/bin/jlink",
      "--module-path", JPKG_HOME + "/jmods",
      "--add-modules", "java.desktop",
      "--strip-debug",
      "--no-header-files",
      "--no-man-pages",
      "--strip-native-commands",
      "--vm=server",
      "--compress=2",
      "--output", "runtime"
    ])
#---------- Build executable
os.chdir (scriptDir)
FREE_ROUTING_NAME = "Freerouting-" + APP_VERSION
runCommand (["rm", "-fr", FREE_ROUTING_NAME + ".app"])
runCommand ([
  JPKG_HOME + "/bin/jpackage",
  "--input", FREEROUTING_DIR + "/build/dist/",
  "--name", FREE_ROUTING_NAME,
  "--main-jar", "freerouting-executable.jar",
  "--type", "app-image",
  "--runtime-image", JPKG_DIR + "/runtime",
  "--app-version", APP_VERSION
])
#---------- Sign executable
runCommand ([
  "/usr/bin/codesign",
  "--force",
  "--sign", developerIDString,
  "--deep",
  FREE_ROUTING_NAME + ".app"
])
#---------- Display executable signature
runCommand ([
  "/usr/bin/codesign",
  "-dv",
  "--verbose=4",
  FREE_ROUTING_NAME + ".app"
])
#---------- Verify executable signature
runCommand ([
  "/usr/bin/codesign",
  "--verify",
  "--deep",
  "--strict",
  "--verbose=1",
  FREE_ROUTING_NAME + ".app"
])
#---------- Distribution directory
DISTRIBUTION_DIR = "Freerouting-" + APP_VERSION
runCommand (["/bin/rm", "-rf", DISTRIBUTION_DIR])
runCommand (["/bin/rm", "-f", FREE_ROUTING_NAME + ".dmg"])
runCommand (["/bin/mkdir", DISTRIBUTION_DIR])
#---------- Build PKG
PACKAGE_FILE = FREE_ROUTING_NAME + ".pkg"
if DMG_CONTAINS_PKG :
  runCommand ([
    "/usr/bin/productbuild",
    "--component-compression", "auto",
    "--component", FREE_ROUTING_NAME + ".app",
    "/Applications",
    PACKAGE_FILE
  ])
#---------- Build DMG
if DMG_CONTAINS_APP:
  runCommand (["/bin/cp", "-r", FREE_ROUTING_NAME + ".app", DISTRIBUTION_DIR])
if DMG_CONTAINS_PKG:
  runCommand (["/bin/cp", PACKAGE_FILE, DISTRIBUTION_DIR])
runCommand ([
  "/usr/bin/hdiutil",
  "create",
  "-srcfolder", FREE_ROUTING_NAME,
  FREE_ROUTING_NAME + ".dmg",
  "-fs", "HFS+"
])
#---------- Clean
if DMG_CONTAINS_PKG :
  runCommand (["/bin/rm", PACKAGE_FILE])
runCommand (["/bin/rm", "-rf", DISTRIBUTION_DIR])
print (BLUE + "Done!" + ENDC)

#------------------------------------------------------------------------------

**Comment by dComposer** [comment]
I'm getting this same exact issue. I'm on Monterey so maybe that's what's causing it?

**Comment by andrasfuchs** [comment]
I don't know, but after looking it up [again](https://discussions.apple.com/thread/253301644), my best guess is still that I would need a Apple developer license to fix this.

**Comment by andrasfuchs** [comment]
Guys, can I ask your help with this issue?
I would need someone who has an active Apple developer license and who could sign the macOS installer using our script, and test the signed installer on macOS.

**Comment by UserC2** [comment]
> I'm getting this same exact issue. I'm on Monterey so maybe that's what's causing it?

I have the same issue on Big Sur, so I don't think that's related.
